import React, { useEffect, useMemo, useState } from 'react';
import { Cloud, CloudLightning, CloudRain, CloudSun, Search, Sun, Wind, Droplets, ArrowUpRight, Calendar, Clock, RefreshCw, MapPin } from 'lucide-react';
import { sound } from '../utils/sound';
import { translations } from '../utils/translations';
import { getWeatherByCity, decodeWeatherCode } from '../utils/weatherService';

const icons = { Sun, Cloud, CloudSun, CloudRain, CloudLightning };
function IconFor({ code, isDay = 1 }) { const key = decodeWeatherCode(code, isDay).icon; const Icon = icons[key] || Cloud; return <Icon className="w-6 h-6 text-blue-600" />; }
function fmtTime(value, timezone) { try { return new Intl.DateTimeFormat(undefined, { hour: '2-digit', minute: '2-digit', timeZone: timezone === 'auto' ? undefined : timezone }).format(new Date(value)); } catch { return String(value).slice(11, 16); } }

export default function ForecastScreen({ currentLang, initialQuery }) {
  const t = translations[currentLang] || translations.en;
  const [query, setQuery] = useState(initialQuery || 'Visakhapatnam'); const [payload, setPayload] = useState(null); const [selectedDay, setSelectedDay] = useState(0); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = async (event, value = query) => { event?.preventDefault(); if (!value.trim()) return; setLoading(true); setError(''); try { setPayload(await getWeatherByCity(value)); setSelectedDay(0); } catch (e) { setError(e.message || 'Unable to retrieve forecast.'); } finally { setLoading(false); } };
  useEffect(() => { const q = initialQuery || 'Visakhapatnam'; setQuery(q); load(null, q); }, [initialQuery]);
  const hourly = useMemo(() => { const h = payload?.hourly; if (!h?.time?.length) return []; const start = Math.max(0, h.time.findIndex((time) => time >= payload?.current?.time)); return Array.from({ length: 8 }, (_, offset) => { const i = Math.min(h.time.length - 1, start + offset * 2); return { time: h.time[i], temp: h.temperature_2m[i], code: h.weather_code[i], rainProb: h.precipitation_probability?.[i] ?? 0, rain: h.precipitation?.[i] ?? 0 }; }); }, [payload]);
  const daily = payload?.daily; const loc = payload?.location; const source = payload?.source || 'Waiting for forecast';
  return <div className="w-full min-h-[calc(100vh-73px)] p-4 sm:p-6 lg:p-8 flex flex-col space-y-6 max-w-7xl mx-auto animate-in fade-in duration-300">
    <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><h1 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight flex items-center gap-2"><CloudSun className="w-7 h-7 text-blue-600" />{t.forecastTitle || 'Atmospheric Forecast Intelligence'}</h1><p className="text-sm text-slate-600 mt-1">Search any village, town, district, or city for a live hourly and 7-day forecast.</p></div><form onSubmit={load} className="flex w-full lg:w-[430px] gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} aria-label="Search location for atmospheric forecast" placeholder="Search village or city" className="w-full rounded-xl border border-blue-200 bg-white px-9 py-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-400" /></div><button disabled={loading} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60">{loading ? <RefreshCw className="w-4 h-4 animate-spin" /> : 'Search'}</button></form></div>
    {error && <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-blue-100 bg-white/80 p-4"><div className="flex items-center gap-3"><MapPin className="w-5 h-5 text-blue-600" /><div><div className="font-black text-slate-900">{loc ? `${loc.name}, ${loc.admin1 || loc.country}` : 'Select a location'}</div><div className="text-xs text-slate-500">{loc ? `${loc.latitude.toFixed(4)}°, ${loc.longitude.toFixed(4)}°` : 'Live atmospheric forecast'}</div></div></div><div className="text-right text-xs"><div className="font-bold text-blue-700">{source}</div><div className="text-slate-500">Updated {payload?.fetchedAt ? new Date(payload.fetchedAt).toLocaleString() : '—'}</div></div></div>
    <section className="glass-panel p-6 rounded-3xl border border-blue-200 bg-white/90 shadow-xl space-y-4"><div className="flex items-center justify-between"><div className="flex items-center space-x-2 text-sm font-bold text-slate-900"><Clock className="w-4 h-4 text-blue-600" /><span>{t.timeline24h || '24-Hour Forecast Timeline'}</span></div><span className="text-[11px] text-slate-600 font-mono font-semibold">HOURLY RESOLUTION</span></div><div className="flex items-center gap-3 overflow-x-auto pb-4 pt-2">{hourly.map((item) => <div key={item.time} className="flex-shrink-0 w-32 p-4 rounded-2xl bg-blue-50/70 border border-blue-200 flex flex-col items-center space-y-2.5 text-center shadow-sm"><span className="text-xs font-mono text-slate-600 font-semibold">{fmtTime(item.time, loc?.timezone)}</span><div className="p-2 rounded-xl bg-blue-100/80 border border-blue-200"><IconFor code={item.code} /></div><span className="text-xl font-black text-slate-900">{Math.round(item.temp)}°C</span><span className="text-[11px] text-slate-700 font-bold">{decodeWeatherCode(item.code).label}</span><div className="w-full bg-blue-200 rounded-full h-1.5 overflow-hidden"><div className="bg-blue-600 h-full rounded-full" style={{ width: `${item.rainProb}%` }} /></div><span className="text-[10px] text-blue-700 font-mono font-bold flex items-center gap-0.5"><CloudRain className="w-3 h-3" />{item.rainProb}%</span></div>)}</div><div className="pt-4 border-t border-blue-100"><div className="flex items-center justify-between text-xs text-slate-700 font-semibold mb-2"><span>Temperature & Rain Intensity Curve</span><span className="flex items-center gap-1.5"><span className="w-2.5 h-1.5 bg-blue-600 rounded-full" /> Temperature (°C)</span></div><div className="h-28 w-full bg-blue-50/80 rounded-2xl p-4 flex items-end justify-between border border-blue-200">{hourly.map((d) => <div key={d.time} className="flex-1 flex flex-col items-center gap-1"><div className="w-full max-w-[28px] bg-gradient-to-t from-blue-600 to-sky-400 rounded-t-md" style={{ height: `${Math.max(12, (d.temp / 40) * 80)}px` }} /><span className="text-[10px] font-mono text-slate-600 font-bold">{fmtTime(d.time, loc?.timezone)}</span></div>)}</div></div></section>
    <section className="glass-panel p-6 rounded-3xl border border-blue-200 bg-white/90 shadow-xl space-y-4"><div className="flex items-center justify-between"><div className="flex items-center space-x-2 text-sm font-bold text-slate-900"><Calendar className="w-4 h-4 text-blue-600" /><span>{t.synoptic7d || '7-Day Synoptic Outlook'}</span></div><span className="text-[11px] text-slate-600 font-mono font-semibold">LIVE FORECAST</span></div><div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-3">{(daily?.time || []).map((day, idx) => { const selected = idx === selectedDay; return <button key={day} onClick={() => { sound.playClick(); setSelectedDay(idx); }} className={`text-left p-4 rounded-2xl border transition-all ${selected ? 'bg-blue-600 text-white border-blue-600 shadow-lg scale-[1.02]' : 'bg-blue-50/60 border-blue-200 hover:border-blue-400'}`}><div className="flex items-center justify-between"><span className="font-bold text-sm">{new Date(day).toLocaleDateString(undefined, { weekday: 'short' })}</span><span className="text-[10px] font-mono">{new Date(day).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</span></div><div className="my-3 flex items-center justify-center"><div className={`p-2.5 rounded-xl border ${selected ? 'bg-white/20 border-white/30' : 'bg-white border-blue-200'}`}><IconFor code={daily.weather_code[idx]} /></div></div><div className="flex items-center justify-between text-xs"><span className="font-black text-base">{Math.round(daily.temperature_2m_max[idx])}°</span><span>{Math.round(daily.temperature_2m_min[idx])}°</span></div><div className="text-[11px] font-bold truncate my-2">{decodeWeatherCode(daily.weather_code[idx]).label}</div><div className="flex items-center justify-between text-[10px] font-mono font-bold px-2 py-1 rounded-lg border"><span className="flex items-center gap-1"><Droplets className="w-2.5 h-2.5" />Rain</span><span>{daily.precipitation_probability_max?.[idx] ?? 0}%</span></div></button>; })}</div>{daily?.time?.[selectedDay] && <div className="mt-4 p-4 rounded-2xl bg-blue-50 border border-blue-200 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3"><div><span className="text-[10px] text-blue-800 font-mono font-bold uppercase tracking-wider">DAY BRIEFING</span><div className="text-sm font-bold text-slate-900 mt-0.5">{new Date(daily.time[selectedDay]).toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })} — max {daily.temperature_2m_max[selectedDay]}°C, min {daily.temperature_2m_min[selectedDay]}°C, precipitation probability {daily.precipitation_probability_max?.[selectedDay] ?? 0}%</div></div><span className="text-xs font-bold text-blue-700 flex items-center gap-1">Live model details <ArrowUpRight className="w-3.5 h-3.5" /></span></div>}</section>
  </div>;
}
